# Site settings
title: "Evamanga"
url-title: "Kỷ Niệm Cuộc Sống"
description: "Nhân Sinh và Triết Lý"
paginate: 100
url: "https://evamanga.net"
permalink: /:year/:month/:title/
future: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_words: 25

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed

gems: [jekyll-paginate]
